from services.response_service import SafeView, command_error
import re

import discord
from discord import app_commands
from discord.ext import commands

from config import INTRODUCTIONS_CHANNEL_ID
from services.server_service import ServerMessageError, upsert_fixed_message




def setting_key_for(channel: discord.TextChannel) -> str:
    # Keep the already-tested introductions key so the existing managed message is reused.
    if channel.id == INTRODUCTIONS_CHANNEL_ID:
        return "server_introductions_message_id"
    return f"server_pinned_message_{channel.id}"


def default_copy_for(channel: discord.TextChannel) -> str:
    if _channel_alias(channel.name) in {'introductions', 'newbies'}:
        return ''
    if _channel_alias(channel.name) == 'welcome':
        from services.onboarding_service import WELCOME_COPY
        return WELCOME_COPY
    if _channel_alias(channel.name) == "choose-your-roles":
        from services.role_panel_service import INTRO
        return INTRO
    if _channel_alias(channel.name) == "looking-for-group":
        return (
            "# 🎮 Looking for Group\n\n"
            "**Find Games. Find Mates. Play Together.**\n\n"
            "Create public or private gaming sessions directly through GamerHQ.\n\n"
            "## 🚀 CREATE AN EVENT\n"
            "Use **Create Event** below or `/lfg create`. Choose your game, title, date, time, player limit and voice reminder.\n\n"
            "🌐 **Public** — posted in LFG so the community can discover and join it.\n"
            "🔒 **Private** — invite only. GamerHQ creates a private event channel visible only to the host, invited/joined players, staff and the bot.\n\n"
            "## 👥 INVITES & SHARING\n"
            "Invite specific players during creation. If they do not have the game role yet, GamerHQ can add it when they confirm the join.\n"
            "🌐 Public events: **Share Event** gives anyone who can see the event its direct Discord link.\n"
            "🔒 Private events: the host can use **Share Invite**. During the Discord-only Beta, new members receive a GamerHQ server invite plus the event access code; existing members only need the event access code. The invite can be regenerated by the host.\n\n"
            "## 🎙️ EVENT SPACE\n"
            "Event voice is created automatically before the start. Private event voice access follows the private participant list.\n\n"
            "Use `/lfg manage` to manage events you created."
        )
    title = channel.name.replace("-", " ").title()
    return f"# 📌 {title}\n\nAdd the official GamerHQ channel information here."


CHANNEL_PLACEHOLDER_RE = re.compile(r"\{([a-zA-Z0-9_-]+)\}")
CHANNEL_MENTION_RE = re.compile(r"<#(\d+)>")


def _channel_alias(name: str) -> str:
    """Normalize decorated Discord channel names to a stable admin placeholder."""
    name = name.lower().strip()
    # GamerHQ channels can be decorated, e.g. "🎮・choose-your-games".
    # Keep only ASCII letters/numbers/hyphens so {choose-your-games} stays stable.
    name = re.sub(r"[^a-z0-9_-]+", "", name)
    return name.strip("-_")


def resolve_channel_placeholders(guild: discord.Guild, text: str) -> str:
    """Turn {channel-name} placeholders into real Discord channel mentions."""
    by_alias: dict[str, list[discord.abc.GuildChannel]] = {}
    for channel in guild.channels:
        if isinstance(channel, (discord.TextChannel, discord.VoiceChannel, discord.ForumChannel)):
            alias = _channel_alias(channel.name)
            if alias:
                by_alias.setdefault(alias, []).append(channel)

    def replace(match: re.Match) -> str:
        alias = _channel_alias(match.group(1))
        matches = by_alias.get(alias, [])
        if len(matches) != 1:
            return match.group(0)
        return matches[0].mention

    return CHANNEL_PLACEHOLDER_RE.sub(replace, text)


def restore_channel_placeholders(guild: discord.Guild, text: str) -> str:
    """Show stored channel mentions as readable {channel-name} placeholders in the editor."""
    def replace(match: re.Match) -> str:
        channel = guild.get_channel(int(match.group(1)))
        if channel is None:
            return match.group(0)
        alias = _channel_alias(channel.name)
        return "{" + (alias or channel.name) + "}"

    return CHANNEL_MENTION_RE.sub(replace, text)


def managed_channel_view(channel: discord.TextChannel):
    """Attach channel-specific persistent controls without coupling server logic to role internals."""
    if _channel_alias(channel.name) == "choose-your-roles":
        from cogs.roles import build_choose_roles_view
        return build_choose_roles_view()
    if _channel_alias(channel.name) == "looking-for-group":
        from cogs.lfg import build_lfg_hub_view
        return build_lfg_hub_view()
    return None


async def refresh_lfg_guide_message(guild: discord.Guild):
    """Refresh the official LFG help message without touching member event posts."""
    from services.lfg_service import find_lfg_channel
    channel = find_lfg_channel(guild)
    if not isinstance(channel, discord.TextChannel):
        return None
    return await upsert_fixed_message(
        channel,
        setting_key=setting_key_for(channel),
        content=resolve_channel_placeholders(guild, default_copy_for(channel)),
        pin=True,
        view=managed_channel_view(channel),
    )


class RoleCleanupSelect(discord.ui.Select):
    def __init__(self, *, candidates, selected_ids: set[int]):
        options = []
        for role, reason in candidates[:25]:
            count = len(role.members)
            description = f"{count} member{'s' if count != 1 else ''} • {reason}"[:100]
            options.append(
                discord.SelectOption(
                    label=role.name[:100],
                    value=str(role.id),
                    description=description,
                    default=role.id in selected_ids,
                )
            )
        super().__init__(
            placeholder="Select roles to remove",
            min_values=0,
            max_values=len(options),
            options=options,
            row=0,
        )

    async def callback(self, interaction: discord.Interaction):
        view = self.view
        view.selected_ids = {int(value) for value in self.values}
        await interaction.response.edit_message(
            content=view.render_content(),
            view=RoleCleanupSelectView(
                guild=view.guild,
                admin_id=view.admin_id,
                candidates=view.candidates,
                selected_ids=view.selected_ids,
            ),
        )


class RoleCleanupSelectView(discord.ui.View):
    def __init__(self, *, guild: discord.Guild, admin_id: int, candidates, selected_ids: set[int] | None = None):
        super().__init__(timeout=180)
        self.guild = guild
        self.admin_id = admin_id
        self.candidates = candidates[:25]
        self.selected_ids = set(selected_ids or set())
        self.add_item(RoleCleanupSelect(candidates=self.candidates, selected_ids=self.selected_ids))

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        if interaction.user.id != self.admin_id:
            await interaction.response.send_message("❌ This cleanup belongs to another admin session.", ephemeral=True)
            return False
        return True

    def render_content(self) -> str:
        selected = [role for role, _ in self.candidates if role.id in self.selected_ids]
        affected = len({member.id for role in selected for member in role.members})
        lines = [
            "**🧹 Role Cleanup**",
            "Select exactly which roles you want to remove.",
            "Nothing is deleted until the final confirmation.",
            "",
            f"Selected: **{len(selected)}** role(s) • **{affected}** unique member(s) affected",
        ]
        if len(self.candidates) >= 25:
            lines.append("ℹ️ Discord shows up to 25 cleanup candidates at once.")
        return "\n".join(lines)

    @discord.ui.button(label="Continue", emoji="➡️", style=discord.ButtonStyle.primary, row=1)
    async def continue_cleanup(self, interaction: discord.Interaction, button: discord.ui.Button):
        if not self.selected_ids:
            await interaction.response.send_message("ℹ️ Select at least one role first.", ephemeral=True)
            return
        selected = [(role, reason) for role, reason in self.candidates if role.id in self.selected_ids]
        await interaction.response.edit_message(
            content=render_cleanup_preview(selected),
            view=ConfirmRoleCleanupView(
                guild=self.guild,
                admin_id=self.admin_id,
                candidates=self.candidates,
                selected_ids=self.selected_ids,
            ),
        )

    @discord.ui.button(label="Back", emoji="⬅️", style=discord.ButtonStyle.secondary, row=1)
    async def back(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.edit_message(
            content="**⚙️ Manage GamerHQ Roles**\nSync required base roles, review the current setup or safely clean up old GamerHQ role duplicates.",
            view=RoleAdminView(guild=self.guild, admin_id=self.admin_id),
        )

    @discord.ui.button(label="Cancel", emoji="✖️", style=discord.ButtonStyle.danger, row=1)
    async def cancel(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.edit_message(content="✖️ Cleanup cancelled. Nothing was deleted.", view=None)
        self.stop()


def render_cleanup_preview(selected) -> str:
    unique_members = {member.id for role, _ in selected for member in role.members}
    lines = [
        "**⚠️ Cleanup Preview**",
        "The following roles will be permanently deleted:",
        "",
    ]
    for role, reason in selected:
        count = len(role.members)
        lines.append(f"• **{role.name}** — 👥 {count} member{'s' if count != 1 else ''}")
        lines.append(f"  ↳ {reason}")
    lines.extend([
        "",
        f"**{len(selected)} role(s)** selected • **{len(unique_members)} unique member(s)** affected",
        "Members using these roles will lose them.",
    ])
    return "\n".join(lines)


class ConfirmRoleCleanupView(discord.ui.View):
    def __init__(self, *, guild: discord.Guild, admin_id: int, candidates, selected_ids: set[int]):
        super().__init__(timeout=180)
        self.guild = guild
        self.admin_id = admin_id
        self.candidates = candidates
        self.selected_ids = set(selected_ids)

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        if interaction.user.id != self.admin_id:
            await interaction.response.send_message("❌ This cleanup belongs to another admin session.", ephemeral=True)
            return False
        return True

    @discord.ui.button(label="Delete Selected Roles", emoji="🗑️", style=discord.ButtonStyle.danger)
    async def confirm(self, interaction: discord.Interaction, button: discord.ui.Button):
        from services.role_service import delete_cleanup_candidates
        await interaction.response.defer(ephemeral=True, thinking=True)
        deleted, failed = await delete_cleanup_candidates(self.guild, self.selected_ids)
        parts = []
        if deleted:
            parts.append("✅ **Deleted:**\n" + "\n".join(f"• {name}" for name in deleted))
        if failed:
            parts.append("⚠️ **Could not delete:**\n" + "\n".join(f"• {name}" for name in failed))
        if not parts:
            parts.append("ℹ️ Nothing needed to be deleted anymore.")
        await interaction.edit_original_response(content="\n\n".join(parts), view=None)
        self.stop()

    @discord.ui.button(label="Back", emoji="⬅️", style=discord.ButtonStyle.secondary)
    async def back(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.edit_message(
            content=RoleCleanupSelectView(
                guild=self.guild,
                admin_id=self.admin_id,
                candidates=self.candidates,
                selected_ids=self.selected_ids,
            ).render_content(),
            view=RoleCleanupSelectView(
                guild=self.guild,
                admin_id=self.admin_id,
                candidates=self.candidates,
                selected_ids=self.selected_ids,
            ),
        )

    @discord.ui.button(label="Cancel", emoji="✖️", style=discord.ButtonStyle.secondary)
    async def cancel(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.edit_message(content="✖️ Cleanup cancelled. Nothing was deleted.", view=None)
        self.stop()


class ConfirmRoleSyncView(discord.ui.View):
    def __init__(self, *, guild: discord.Guild, admin_id: int):
        super().__init__(timeout=180)
        self.guild = guild
        self.admin_id = admin_id

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        if interaction.user.id != self.admin_id:
            await interaction.response.send_message("❌ This sync belongs to another admin session.", ephemeral=True)
            return False
        return True

    @discord.ui.button(label="Confirm Sync", emoji="✅", style=discord.ButtonStyle.success)
    async def confirm(self, interaction: discord.Interaction, button: discord.ui.Button):
        from services.role_service import ensure_base_roles
        await interaction.response.defer(ephemeral=True, thinking=True)
        try:
            resolved, created = await ensure_base_roles(self.guild)
            from services.role_service import ensure_lfg_roles
            from services.role_panel_service import refresh
            await ensure_lfg_roles(self.guild)
            await refresh(self.guild)
        except (discord.HTTPException, ServerMessageError, ValueError) as exc:
            await interaction.edit_original_response(content=f"❌ Role sync failed.\n`{exc}`", view=None)
            return
        created_text = ", ".join(role.name for role in created) if created else "None"
        await interaction.edit_original_response(
            content=(
                f"✅ **Role sync complete.**\n"
                f"Managed base roles: **{len(resolved)}**\n"
                f"Created: {created_text}"
            ),
            view=None,
        )
        self.stop()

    @discord.ui.button(label="Cancel", emoji="✖️", style=discord.ButtonStyle.secondary)
    async def cancel(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.edit_message(content="✖️ Sync cancelled. Nothing was changed.", view=None)
        self.stop()


class RoleAdminView(discord.ui.View):
    def __init__(self, *, guild: discord.Guild, admin_id: int):
        super().__init__(timeout=180)
        self.guild = guild
        self.admin_id = admin_id

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        if interaction.user.id != self.admin_id:
            await interaction.response.send_message("❌ This menu belongs to another admin session.", ephemeral=True)
            return False
        return True

    @discord.ui.button(label="Sync Roles", emoji="🔄", style=discord.ButtonStyle.primary)
    async def sync_roles(self, interaction: discord.Interaction, button: discord.ui.Button):
        from services.role_service import base_role_status, ROLE_GROUPS
        present, missing = base_role_status(self.guild)
        lines = ["**🔄 Role Sync Preview**", ""]
        lines.append(f"✅ Existing/reusable: **{len(present)}**")
        if missing:
            lines.append(f"➕ Missing roles to create: **{len(missing)}**")
            lines.extend(f"• {option.emoji} {option.label}" for _, option in missing)
        else:
            lines.append("➕ Missing roles to create: **0**")
        lines.append("\nNothing changes until you confirm.")
        await interaction.response.edit_message(
            content="\n".join(lines),
            view=ConfirmRoleSyncView(guild=self.guild, admin_id=self.admin_id),
        )

    @discord.ui.button(label="Cleanup Roles", emoji="🧹", style=discord.ButtonStyle.secondary)
    async def cleanup_roles(self, interaction: discord.Interaction, button: discord.ui.Button):
        from services.role_service import cleanup_candidates
        candidates = cleanup_candidates(self.guild)
        if not candidates:
            await interaction.response.edit_message(
                content="✅ **Role Cleanup**\nNo safe GamerHQ role leftovers or duplicates were found.",
                view=RoleAdminView(guild=self.guild, admin_id=self.admin_id),
            )
            return
        view = RoleCleanupSelectView(
            guild=self.guild,
            admin_id=self.admin_id,
            candidates=candidates,
        )
        await interaction.response.edit_message(
            content=view.render_content(),
            view=view,
        )

    @discord.ui.button(label="View Roles", emoji="📋", style=discord.ButtonStyle.secondary)
    async def view_roles(self, interaction: discord.Interaction, button: discord.ui.Button):
        from services.role_service import base_role_status, ROLE_GROUPS
        from database import db
        present, missing = base_role_status(self.guild)
        active_games = [g for g in db.get_selectable_games() if g.get("role_id")]
        lines = ["**📋 GamerHQ Managed Roles**", "", f"**Base roles:** {len(present)} configured / {len(missing)} missing"]
        for group in ROLE_GROUPS:
            names = [role.mention for g, option, role in present if g == group]
            if names:
                lines.append(f"**{group}:** " + " • ".join(names))
        lines.append(f"\n**Active game roles:** {len(active_games)}")
        await interaction.response.edit_message(
            content="\n".join(lines),
            view=RoleAdminView(guild=self.guild, admin_id=self.admin_id),
        )

    @discord.ui.button(label="Cancel", emoji="✖️", style=discord.ButtonStyle.danger, row=1)
    async def cancel(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.edit_message(content="✖️ Role manager closed.", view=None)
        self.stop()




class ServerSetupView(SafeView):
    def __init__(self, *, guild: discord.Guild, owner_id: int):
        super().__init__(timeout=240)
        self.guild = guild
        self.owner_id = owner_id

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        if interaction.user.id != self.owner_id or interaction.user.id != self.guild.owner_id:
            await interaction.response.send_message(
                "❌ Only the Discord server owner can use GamerHQ Server Setup.",
                ephemeral=True,
            )
            return False
        return True

    @discord.ui.button(label="Preview Repairs", emoji="🔍", style=discord.ButtonStyle.secondary)
    async def details(self, interaction: discord.Interaction, button: discord.ui.Button):
        from services.health_service import scan, summary
        await interaction.response.defer(ephemeral=True)
        findings = await scan(self.guild, interaction.client)
        await interaction.edit_original_response(
            content=summary(findings).replace('# GamerHQ Health', '# REPAIR PREVIEW'),
            view=ServerSetupDetailsView(guild=self.guild, owner_id=self.owner_id),
        )

    @discord.ui.button(label="Repair / Setup", emoji="🔧", style=discord.ButtonStyle.primary)
    async def repair(self, interaction: discord.Interaction, button: discord.ui.Button):
        from services.server_setup_service import analyze_server
        report = analyze_server(self.guild)
        await interaction.response.edit_message(
            content=(
                "# 🔧 Repair GamerHQ Server\n\n"
                "Apply the focused onboarding update?\n\n"
                "Migrate old welcome to COMMUNITY/newbies; create the clean START HERE/welcome; move LFG to START HERE, tournaments/giveaways to EVENTS; add guide, private staff suggestions and the read-only Support / MARKETPLACE channels.\n"
                "Custom areas and game categories are left untouched.\n\n"
                "Confirm to continue."
            ),
            view=ConfirmServerRepairView(guild=self.guild, owner_id=self.owner_id),
        )

    @discord.ui.button(label="Close", emoji="✖️", style=discord.ButtonStyle.danger)
    async def close(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.edit_message(content="✖️ Server setup closed. Nothing was changed.", view=None)
        self.stop()


class ServerSetupDetailsView(SafeView):
    def __init__(self, *, guild: discord.Guild, owner_id: int):
        super().__init__(timeout=240)
        self.guild = guild
        self.owner_id = owner_id

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        if interaction.user.id != self.owner_id or interaction.user.id != self.guild.owner_id:
            await interaction.response.send_message("❌ Only the server owner can use this setup session.", ephemeral=True)
            return False
        return True

    @discord.ui.button(label="Back", emoji="⬅️", style=discord.ButtonStyle.secondary)
    async def back(self, interaction: discord.Interaction, button: discord.ui.Button):
        from services.server_setup_service import analyze_server, render_summary
        report = analyze_server(self.guild)
        await interaction.response.edit_message(
            content=render_summary(self.guild, report),
            view=ServerSetupView(guild=self.guild, owner_id=self.owner_id),
        )

    @discord.ui.button(label="Repair / Setup", emoji="🔧", style=discord.ButtonStyle.primary)
    async def repair(self, interaction: discord.Interaction, button: discord.ui.Button):
        from services.server_setup_service import analyze_server
        report = analyze_server(self.guild)
        await interaction.response.edit_message(
            content=(
                "# 🔧 Repair GamerHQ Server\n\n"
                "Apply the focused onboarding update?\n\n"
                "Updates onboarding channels, posting permissions and canonical guides. Only identifiable obsolete bot pins are removed."
            ),
            view=ConfirmServerRepairView(guild=self.guild, owner_id=self.owner_id),
        )

    @discord.ui.button(label="Close", emoji="✖️", style=discord.ButtonStyle.danger)
    async def close(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.edit_message(content="✖️ Server setup closed. Nothing was changed.", view=None)
        self.stop()


class ConfirmServerRepairView(SafeView):
    def __init__(self, *, guild: discord.Guild, owner_id: int):
        super().__init__(timeout=180)
        self.guild = guild
        self.owner_id = owner_id
        self.running = False

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        if interaction.user.id != self.owner_id or interaction.user.id != self.guild.owner_id:
            await interaction.response.send_message("❌ Only the server owner can confirm server changes.", ephemeral=True)
            return False
        return True

    @discord.ui.button(label="Confirm Repair", emoji="✅", style=discord.ButtonStyle.success)
    async def confirm(self, interaction: discord.Interaction, button: discord.ui.Button):
        if self.running:
            await interaction.response.send_message("⏳ Setup is already running.", ephemeral=True)
            return
        self.running = True
        for item in self.children:
            item.disabled = True
        await interaction.response.edit_message(content="⏳ Updating GamerHQ core channels, guides and suggestions…", view=self)

        from services.server_setup_service import analyze_server, render_summary, repair_server
        created, failed = await repair_server(self.guild, interaction.client)
        from services.music_bot_service import sync_music_access, render_music_result
        from services.game_area_cleanup import scan_areas
        music_result = await sync_music_access(self.guild)
        areas, _ = scan_areas(self.guild)
        report = analyze_server(self.guild)

        role_notes = [entry.removeprefix('[BOT ROLES] ') for entry in created if entry.startswith('[BOT ROLES] ')]
        created = [entry for entry in created if not entry.startswith('[BOT ROLES] ')]
        lines = ["# GamerHQ Server Repair Finished", "", "**BOT ROLE ASSIGNMENT**", *role_notes, "", render_music_result(music_result), "",
                 f"**GAME AREA CLEANUP**\nCandidates available: {sum(row['safe'] for row in areas)}\nUse `/server cleanup-game-areas` to review them. Nothing was deleted.", ""]
        if created:
            lines.append(f"**Updated ({len(created)}):**")
            lines.extend(f"• {entry}" for entry in created[:8])
            if len(created) > 8:
                lines.append(f"• …and {len(created) - 8} more")
        else:
            lines.append("**Updated:** No structural changes needed.")
        if failed:
            lines.extend(["", f"**⚠️ Failed ({len(failed)}):**"])
            lines.extend(f"• {entry}" for entry in failed[:15])
        lines.extend(["", render_summary(self.guild, report)])
        await interaction.edit_original_response(
            content="\n".join(lines)[:2000],
            view=ServerSetupView(guild=self.guild, owner_id=self.owner_id),
        )
        import logging, time
        logging.getLogger(__name__).warning("repair timestamp=%s actor=%s guild=%s updated=%s failures=%s", int(time.time()), interaction.user.id, self.guild.id, len(created), len(failed) + len(music_result["failures"]))
        self.stop()

    @discord.ui.button(label="Cancel", emoji="✖️", style=discord.ButtonStyle.secondary)
    async def cancel(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.edit_message(content="✖️ Repair cancelled. Nothing was changed.", view=None)
        self.stop()

class AdoptChannelView(SafeView):
    def __init__(self, guild, draft):
        super().__init__(timeout=180)
        self.guild, self.draft = guild, draft
        self.finished = False

    async def interaction_check(self, interaction):
        from services.channel_adoption_service import authorize
        try:
            authorize(self.guild, interaction.user)
            if self.finished or interaction.user.id != self.draft['actor_id']:
                raise ServerMessageError('Only the preview author can use this active adoption session.')
        except ServerMessageError as exc:
            await interaction.response.send_message(str(exc), ephemeral=True)
            return False
        return True

    @discord.ui.button(label='Confirm Adoption', emoji='✅', style=discord.ButtonStyle.success)
    async def confirm_adoption(self, interaction, button):
        if not await self.interaction_check(interaction):
            return
        from services.channel_adoption_service import confirm
        self.finished = True
        await interaction.response.defer()
        try:
            changed = await confirm(self.guild, interaction.user, self.draft, confirmed=True)
            text = 'Desired state saved. Discord was not changed.' if changed else 'No differences to adopt. Nothing changed.'
        except (ServerMessageError, discord.HTTPException) as exc:
            text = str(exc)
        await interaction.edit_original_response(content=text, view=None)
        self.stop()

    @discord.ui.button(label='Cancel', style=discord.ButtonStyle.secondary)
    async def cancel_adoption(self, interaction, button):
        if not await self.interaction_check(interaction):
            return
        self.finished = True
        await interaction.response.edit_message(content='Adoption cancelled. Nothing changed.', view=None)
        self.stop()


class ServerAdmin(commands.Cog):
    cog_app_command_error = command_error
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    async def refresh_default_managed_messages(self, guild: discord.Guild):
        from services.onboarding_service import refresh_onboarding
        await refresh_onboarding(guild)

    server = app_commands.Group(
        name="server",
        description="GamerHQ server administration",
        default_permissions=discord.Permissions(administrator=True),
    )

    @server.command(name='health', description='Owner/admin: read-only diagnostics and acceptance-test details.')
    async def health(self, interaction: discord.Interaction):
        from services.game_area_cleanup import authorized
        from services.health_service import scan, summary
        from cogs.health import HealthView
        if not interaction.guild or not authorized(interaction.guild, interaction.user):
            return await interaction.response.send_message('❌ Owner or administrator access required.', ephemeral=True)
        await interaction.response.defer(ephemeral=True)
        findings = await scan(interaction.guild, interaction.client)
        await interaction.followup.send(summary(findings), view=HealthView(interaction.guild, interaction.user.id, findings), ephemeral=True)

    @server.command(name='adopt', description='Owner/admin: preview and adopt selected public managed channel properties.')
    @app_commands.guild_only()
    @app_commands.choices(aspect=[app_commands.Choice(name=label, value=value) for label, value in
        [('Name / emoji', 'name'), ('Category', 'category'), ('Position', 'position'), ('All supported properties', 'all')]])
    async def adopt(self, interaction: discord.Interaction, channel: discord.TextChannel, aspect: str = 'all'):
        from services.channel_adoption_service import preview, render
        await interaction.response.defer(ephemeral=True)
        try:
            draft = await preview(interaction.guild, interaction.user, channel.id, aspect)
            await interaction.followup.send(render(interaction.guild, draft),
                view=AdoptChannelView(interaction.guild, draft), ephemeral=True,
                allowed_mentions=discord.AllowedMentions.none())
        except (ServerMessageError, discord.HTTPException) as exc:
            await interaction.followup.send(str(exc), ephemeral=True)

    @server.command(name='instant-gaming', description='Admin: sync four Instant Gaming feeds, permissions and managed pins.')
    @app_commands.checks.has_permissions(administrator=True)
    async def instant_gaming(self, interaction: discord.Interaction):
        from services.instant_gaming_service import sync
        if not interaction.guild or not interaction.user.guild_permissions.administrator:
            return await interaction.response.send_message('Administrator access required.', ephemeral=True)
        await interaction.response.defer(ephemeral=True)
        try:
            text = await sync(interaction.guild)
        except (discord.HTTPException, ServerMessageError) as exc:
            text = str(exc)
        await interaction.followup.send(text, ephemeral=True)

    @server.command(name='music-bots-role', description='Admin: configure the existing dedicated Music Bots role.')
    @app_commands.checks.has_permissions(administrator=True)
    async def music_bots_role(self, interaction: discord.Interaction, role: discord.Role):
        from database import db
        from services.music_bot_service import role_key, DENIED_RIGHTS
        if not interaction.guild or not interaction.user.guild_permissions.administrator:
            return await interaction.response.send_message('Administrator access required.', ephemeral=True)
        if role.is_default() or role.managed or any(getattr(role.permissions, name) for name in DENIED_RIGHTS):
            return await interaction.response.send_message('Select a dedicated non-managed role without administrator/moderation permissions.', ephemeral=True)
        db.set_setting(role_key(interaction.guild), role.id)
        await interaction.response.send_message(f'Music Bots role configured: {role.mention}. Run `/server setup` to sync access.', ephemeral=True)

    @server.command(name='cleanup-game-areas', description='Owner/admin: preview unused managed game areas before confirming cleanup.')
    @app_commands.checks.has_permissions(administrator=True)
    async def cleanup_game_areas(self, interaction: discord.Interaction):
        from services.game_area_cleanup import authorized, scan_areas
        from cogs.game_area_cleanup import CleanupPreview
        if not interaction.guild or not authorized(interaction.guild, interaction.user):
            return await interaction.response.send_message('Owner or administrator access required.', ephemeral=True)
        await interaction.response.defer(ephemeral=True, thinking=True)
        rows, unknown = scan_areas(interaction.guild)
        rows.sort(key=lambda row: (not row['safe'], row['game']['name'].casefold()))
        view = CleanupPreview(interaction.guild, interaction.user.id, rows, unknown)
        await interaction.edit_original_response(content=view.content(), view=view)


    @server.command(name="setup", description="Owner only: inspect and repair core channels, guides and private suggestions.")
    async def server_setup(self, interaction: discord.Interaction):
        if not interaction.guild:
            await interaction.response.send_message("❌ This command can only be used inside a Discord server.", ephemeral=True)
            return
        if interaction.user.id != interaction.guild.owner_id:
            await interaction.response.send_message(
                "❌ **Owner only.** `/server setup` can only be used by the Discord server owner.",
                ephemeral=True,
            )
            return

        from services.health_service import scan, summary
        await interaction.response.defer(ephemeral=True)
        findings = await scan(interaction.guild, interaction.client)
        await interaction.followup.send(
            summary(findings).replace('# GamerHQ Health', '# SERVER CHECK'),
            view=ServerSetupView(guild=interaction.guild, owner_id=interaction.user.id),
            ephemeral=True,
        )

    @server.command(name="roles", description="Admin: sync, review and safely clean up GamerHQ-managed roles.")
    @app_commands.checks.has_permissions(administrator=True)
    async def roles(self, interaction: discord.Interaction):
        if not interaction.guild:
            await interaction.response.send_message("❌ This command can only be used inside the GamerHQ server.", ephemeral=True)
            return
        await interaction.response.send_message(
            "**⚙️ Manage GamerHQ Roles**\nSync required base roles, review the current setup or safely clean up old GamerHQ role duplicates.",
            view=RoleAdminView(guild=interaction.guild, admin_id=interaction.user.id),
            ephemeral=True,
        )

    @server.command(name="sync-support", description="Admin: sync and pin Support and partner messages.")
    @app_commands.checks.has_permissions(administrator=True)
    async def sync_support(self, interaction: discord.Interaction):
        if not interaction.guild or not interaction.user.guild_permissions.administrator:
            return await interaction.response.send_message('Administrator access required.', ephemeral=True)
        from services.support_service import sync_support_messages
        await interaction.response.defer(ephemeral=True)
        result = await sync_support_messages(interaction.guild, order=True)
        if result is None:
            text = 'Support channel is not configured. Ask the owner to run `/server setup` first.'
        else:
            text = f'Synchronized {len(result["messages"])} support/partner messages.'
            if result.get('manual_review_channels'):
                text += ' MANUAL_REVIEW: legacy partner channels/custom content retained; inspect before removing.'
            if result.get('retained_messages'):
                text += ' Unrelated legacy message mappings retained for manual review.'
            if result.get('retained_categories'):
                text += ' Nonempty legacy Support category retained; move/review its channels first.'
            if result['pin_failures']:
                text += ' Could not pin: ' + ', '.join(result['pin_failures']) + '. Check permissions and retry.'
        await interaction.followup.send(text, ephemeral=True)

    @server.command(name="pinned-messages", description="Owner/admin: edit GamerHQ-managed pinned messages and buttons.")
    async def pinned_messages(self, interaction: discord.Interaction):
        from cogs.managed_messages import open_editor
        await open_editor(interaction)


async def setup(bot: commands.Bot):
    await bot.add_cog(ServerAdmin(bot))


async def refresh_future_community_messages(guild: discord.Guild):
    """Keep the V27 tournament/giveaway coming-soon pins current."""
    copies = {
        "tournaments": (
            "# 🏆 GamerHQ Tournaments\n\n"
            "Community tournaments are coming to GamerHQ!\n\n"
            "As the community grows, we'll start hosting tournaments across different games — "
            "compete, team up and play for the win. 🏆\n\n"
            "**More details coming as GamerHQ grows. 🚀**"
        ),
        "giveaways": (
            "# 🎁 GamerHQ Giveaways\n\n"
            "Giveaways are coming to GamerHQ!\n\n"
            "As our community grows, we'll introduce community giveaways, special events and rewards "
            "for GamerHQ members. 🎉\n\n"
            "**Stay tuned — more is coming. 🚀**"
        ),
    }
    results = []
    for alias, content in copies.items():
        channel = next((ch for ch in guild.text_channels if _channel_alias(ch.name) == alias), None)
        if not isinstance(channel, discord.TextChannel):
            continue
        message = await upsert_fixed_message(
            channel,
            setting_key=f"server_future_{alias}_message_id",
            content=content,
            pin=True,
            view=None,
        )
        results.append(message)
    return results
